export default {
  zkh: require('../../static/img/(.png'),
  ykh: require('../../static/img/).png'),
  zfkh: require('../../static/img/[.png'),
  yfkh: require('../../static/img/].png'),
  abs: require('../../static/img/abs.png'),
  back: require('../../static/img/back.png'),
  dback: require('../../static/img/dback.png'),
  cuadrado: require('../../static/img/cuadrado.png'),
  dshift: require('../../static/img/dshift.png'),
  fraccion: require('../../static/img/fraccion.png'),
  keyboard: require('../../static/img/keyboard.png'),
  potencia: require('../../static/img/potencia.png'),
  raiz: require('../../static/img/raiz.png'),
  raiz2: require('../../static/img/raiz2.png'),
  shift: require('../../static/img/shift.png'),
  tercera: require('../../static/img/tercera.png'),
  write: require('../../static/img/write.png'),
  write_no: require('../../static/img/write-no.png'),
  keyboard_no: require('../../static/img/keyboard-no.png'),
  penicon: require('../../static/img/penicon.png')
}